version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: .
    depends_on:
      - postgres
      - dynamodb
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    volumes:
      - ./notes:/opt/notes-app/notes
      - ./public:/opt/notes-app/public
      - ./scripts:/opt/notes-app/scripts
      - ./server:/opt/notes-app/server
      - ./src:/opt/notes-app/src
      - ./credentials.js:/opt/notes-app/credentials.js

volumes:
  db:
